# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DBIMonitor__new <- function(ends, releases, attributes, resources, dbClear, dbAppend) {
    .Call(`_simmer_mon_DBIMonitor__new`, ends, releases, attributes, resources, dbClear, dbAppend)
}

